name: Update

on:
  push:
  schedule:
    - cron: 30 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        git config --global user.name HashVPN
        git config --global user.email linnazhe510@gmail.com
        git checkout --orphan latest_branch
        git add -A
        git commit -am "Update"
        git branch -D main
        git branch -m main
        git push -f origin main
